# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world at `date`!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          run: ls -l
          
      - name: Load war to Tomcat
        #run: curl --upload-file sample.war "https://lab.code.eng.br:8080/FTT-WAR-DEPLOYER/wardeploy?TOMCAT_USER=${{ secrets.TOMCAT_USER }}&TOMCAT_PWD=${{ secrets.TOMCAT_PWD }}&TOMCAT_TOKEN=${{ secrets.TOMCAT_TOKEN }}"
        #run: curl https://lab.code.eng.br:8080/FTT-WAR-DEPLOYER/wardeploy?TOMCAT_USER=${{ secrets.TOMCAT_USER }}&TOMCAT_PWD=${{ secrets.TOMCAT_PWD }}&TOMCAT_TOKEN=${{ secrets.TOMCAT_TOKEN }}
        run: curl --upload-file sample.war "https://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PWD }}@lab.code.eng.br:8080/manager/deploy?path=/sample"

